"""Add trend_signals table.

Revision ID: c4d5e6f7a8b9
Revises: b3c4d5e6f7a8
Create Date: 2026-07-12 00:00:00.000001

Trend Agent memory pass: trend signals were never persisted to Postgres —
they only ever lived inside a single run's state and vanished afterward, so
the agent started cold every run with no way to tell whether a keyword had
already been flagged, how its score was moving over time, or whether it had
already raised a critical alert for it recently. This migration adds the
table and closes a second, smaller gap: `evidence` and
`is_new_product_opportunity` were already being generated by the LLM every
run but were being dropped before ever reaching state (see
agents/trend/graph.py::write_state_outputs) — now persisted too.
"""
from typing import Sequence, Union
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op

revision: str = "c4d5e6f7a8b9"
down_revision: Union[str, None] = "b3c4d5e6f7a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on:    Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "trend_signals",
        sa.Column("id",       postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("run_id",   sa.String(36),  nullable=False),
        sa.Column("brand_id", sa.String(255), nullable=False),

        sa.Column("keyword",  sa.String(255), nullable=False),
        sa.Column("platform", sa.String(30),  nullable=False),

        sa.Column("score",     sa.Float(),    nullable=False, server_default="0"),
        sa.Column("direction", sa.String(20), nullable=False, server_default="rising"),

        sa.Column("matched_sku", sa.String(255), nullable=True),
        sa.Column("evidence",    sa.Text(),      nullable=True),

        sa.Column("is_new_product_opportunity", sa.Boolean(), nullable=False, server_default="false"),

        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    op.create_index("ix_trend_signals_run_id",      "trend_signals", ["run_id"])
    op.create_index("ix_trend_signals_brand_id",    "trend_signals", ["brand_id"])
    op.create_index("ix_trend_signals_keyword",     "trend_signals", ["keyword"])
    op.create_index("ix_trend_signals_matched_sku", "trend_signals", ["matched_sku"])


def downgrade() -> None:
    op.drop_index("ix_trend_signals_matched_sku", table_name="trend_signals")
    op.drop_index("ix_trend_signals_keyword",     table_name="trend_signals")
    op.drop_index("ix_trend_signals_brand_id",    table_name="trend_signals")
    op.drop_index("ix_trend_signals_run_id",      table_name="trend_signals")
    op.drop_table("trend_signals")